### ISSUE TITLE
Expression OA not working

### ISSUE THREAD

**Issue by draciti** [WormBase/caltech-curation-services#17]
Tested on 2023-01-13
When trying to create a new object a get a message JSON parse failed

<img width="491" alt="Screen Shot 2023-01-13 at 10 02 18 AM" src="https://user-images.githubusercontent.com/901243/212369548-7efc180d-d0a7-4553-8632-59436ec67228.png">

**Comment by azurebrd** [comment]
Should be fixed now.  @draciti do you want to test it or should I close it ?

**Comment by draciti** [comment]
working well, thanks @azurebrd !

**Comment by azurebrd** [comment]
cool ! @draciti
