### ISSUE TITLE
Dockerize aCeDB

### ISSUE THREAD

**Issue by azurebrd** [WormBase/caltech-curation-services#28]
Dockerize acedb.  Talk to Wen + Raymond about what's possible, talk to curators about what they want to do besides testing data.  Kimberly's looking into what needs to be extracted from acedb for postgres.

**Comment by valearna** [comment]
acedb successfully installed with its own docker image. New docker-compose service to manage the acedb container. No display available in docker, so only tace is available, at least for now. No volumes mounted, but we need to figure out which files need to be shared between the curation and acedb containers

**Comment by azurebrd** [comment]
:nod:  we need to work out what the use cases are.  Kimberly is looking into data extraction from acedb (I think tace-only is enough, but not sure, hopefully we don't need data extraction at all).  We'll have to hear from curators whether they want to be able to test their files there (probably not for tazendra migration). 
For non-tazendra migration, to get rid of spica, I don't know what other things are needed by curators.

**Comment by valearna** [comment]
Sounds good, thanks @azurebrd. I'll talk about this to the group on Thursday. Should we ask Raymond to try using the dockerized acedb to get a better idea of the initial requirements?

**Comment by azurebrd** [comment]
Talking to the group sounds good @valearna .  Asking Raymond and Wen to use it might be good ?  But just asking Raymond as a starting point for sure seems good.

**Comment by valearna** [comment]
Great, thanks @azurebrd

**Comment by valearna** [comment]
Set up X11 forwarding from host to docker container to display acedb GUI by following this guide: https://www.howtogeek.com/devops/how-to-run-gui-applications-in-a-docker-container/

**Comment by valearna** [comment]
@raymond91125 @azurebrd I'm setting up docker to provide aCeDB both as a standalone service (for local deployments) and as part of the main docker instance where curators will ssh into (so that they will be able to use acedb on a server through ssh X11 forwarding). Does this sound useful to you?

**Comment by azurebrd** [comment]
@valearna sure ?  I think we'd have to ask the curators.  At the moment I don't think I need acedb.  But there might be something in the scripts in tazendra that use acedb, and we haven't gotten to them yet.

**Comment by valearna** [comment]
Thanks @azurebrd. Let's ask the curators on Thursday and then we can adjust the setup accordingly.

**Comment by valearna** [comment]
useful guide to deploy with docker on remote server and forward X11 through ssh: https://blog.yadutaf.fr/2017/09/10/running-a-graphical-app-in-a-docker-container-on-a-remote-server/

**Comment by valearna** [comment]
simpe gist on how to enable X11 forwarding through ssh in docker - now implemented in the `curation` docker image

**Comment by valearna** [comment]
This is ready for more testing by curators

**Comment by valearna** [comment]
Try to enable compression to speed up things

**Comment by valearna** [comment]
closing this as done as acedb related errors are being addressed in #56
