### ISSUE TITLE
Add monitoring tools to db

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#3]
- Prometheus (maybe this is not necessary for postgres since grafana can connect directly to the db: https://grafana.com/docs/grafana/latest/datasources/postgres/)
- postgresql prometheus exporter (if needed)
- grafana (write config to loacal volume?)

**Comment by valearna** [comment]
Grafana works directly with postgresql without prometheus. Added grafana docker image to the docker-compose file

**Comment by valearna** [comment]
Reopening this issue after testing grafana. We need to add prometheus in order to monitor postgresql status.

**Comment by valearna** [comment]
Added prometheus and postgresql exporter. @azurebrd I deployed the stack on cervino. We should try to backup the grafana_storage volume to be ready for production

**Comment by azurebrd** [comment]
@valearna cool :)
