### ISSUE TITLE
add pg_dump to curation docker image

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#33]

**Comment by valearna** [comment]
@azurebrd pg_dump and psql installed on the curation docker image and added a new perl module installer to speed up docker image build process

**Comment by azurebrd** [comment]
Hi @valearna .  I see that pg_dump is installed, and I can which + man it, but if I try to use it
`pg_dump caltech_curation > blah.pg                                                                           Thu 23 22:48:21
pg_dump: [archiver (db)] connection to database "caltech_curation" failed: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?`

**Comment by valearna** [comment]
Fixed by changing postgres version of the main DB from 13 to 11, which is the version installed on the curation docker image. @azurebrd you'll need to remove the db volume (or run `docker-compose down -v` to remove all containers and volumes), restart the db container (`docker-compose up -d db`) and reload the db from a dump to restart the DB

**Comment by azurebrd** [comment]
Thanks @valearna !  Something didn't quite work, and I'm not sure what to do about it

 docker-compose down -v                                                                                        
WARNING: The DISPLAY variable is not set. Defaulting to a blank string.
Stopping caltech-curation-services-juancarlos_curation_1 ... done
Removing caltech-curation-services-juancarlos_curation_1 ... done
Removing network caltech-curation-network
ERROR: error while removing network: network caltech-curation-network id c3d0dfa71617e588fa868f4214fc008fea7bc436a36275427c87601521019a8f has active endpoints

I'm not sure if that's supposed to go down or not

**Comment by valearna** [comment]
It's probably because I have other docker containers outside your .env specific configuration running. I stopped everything and now you should be able to rebuild and restart your containers

**Comment by azurebrd** [comment]
Great, thanks @valearna, it's working !  
Also, I remembered we were originally planning to meet Monday to test why dockerized was slower than tazendra for mapping author names to person names.  We can just meet and decide what's worth talking about though
