### ISSUE TITLE
Install get_nameserver_genes script with dependencies (needs Todd)

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#34]
This is the script from /home/postgres/work/pgpopulation/obo_oa_ontologies/geneace/get_nameserver_genes.sh

```
#!/bin/bash

export WB_DB_URI="datomic:ddb://us-east-1/WSNames/wormbase"
java -cp wb-names-export.jar clojure.main -m wormbase.names.export
gene genes.csv

It seems to require 

# install java8
#
# sudo apt-get install awscli
# aws configure
#   AWS Access Key ID [None]: 
#   AWS Secret Access Key [None]: 
# (goes into ~/.aws/config   could also have in ~/.aws/credentials)
#
# get the exporter :
# aws s3 ls s3://wormbase/names/exporter/
# aws s3 cp s3://wormbase/names/exporter/wb-names-export.jar
# wb-names-export.jar
```

**Comment by valearna** [comment]
I'll try to install the default java jdk on debian 10, which is probably different than java8, but should support older versions of java code. We'll need to test the script together @azurebrd as I'm not sure how if works.

**Comment by azurebrd** [comment]
Sounds good, thanks @valearna

**Comment by valearna** [comment]
WB AWS credentials were blocked. We are waiting for new credentials to test this script

**Comment by azurebrd** [comment]
Paulo set up something else, and that's working, so we don't need this
