### ISSUE TITLE
Deploy stack on AWS

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#5]
I know that it's still early and we haven't decided where to deploy the services, but using docker swarm or amazon ECS seems the best solution to me. I found this article and I'm pasting it here for the future: https://aws.amazon.com/blogs/containers/migrating-from-docker-swarm-to-amazon-ecs-with-docker-compose/

**Comment by valearna** [comment]
Finalize the deployment on prod. Also add a shared .env file like the one on dev

**Comment by valearna** [comment]
@azurebrd I've started the deployment to prod. I'm copying /usr/caltech_curation_files to prod before starting the docker containers, but we should talk about transitioning to prod if you have time next week

**Comment by azurebrd** [comment]
Sounds great, thanks @valearna !

**Comment by valearna** [comment]
@azurebrd prod is up at https://caltech-curation.textpressolab.com
