### ISSUE TITLE
Grafana does not work with current apache configuration

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#51]
Figure out how to reach grafana on port 3000 using apache config

**Comment by valearna** [comment]
@azurebrd I enabled grafana using a reverse proxy in apache. I tested it by modifying the config directly inside docker on dev but we'll need to redeploy to make sure everything is ok

**Comment by azurebrd** [comment]
Thanks @valearna .  Not sure what this was for, but let me know if I should rebuild/restart dev (or prod)

**Comment by valearna** [comment]
oh, it's to enable access to the grafana interface, which can be set up to monitor the db and the pipelines and send alerts when something goes wrong. Yes, we should redeploy dev and prod. Grafana will be available at https://caltech-curation-dev.textpressolab.com/grafana. For prod I still have to configure and start the service, but for now I want to test it on dev

**Comment by azurebrd** [comment]
gotcha.  dev is redeployed now.  Thanks @valearna

**Comment by valearna** [comment]
This is now working on prod
