### ISSUE TITLE
Send email using an external smtp server

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#61]
Uninstall sendmail and use an external smtp connection to send emails

**Comment by valearna** [comment]
The docker configuration is working and I believe @azurebrd modified most (if not all) the forms to use a new perl module to send emails through gmail

**Comment by azurebrd** [comment]
Thanks @valearna .  I modified the user submission/update forms on the site map.  No one else could think of anything else that sent emails, so it should be good until people catch a script or something like that.

**Comment by valearna** [comment]
Cool, we can close this issue and open bugs in the future if needed
