### ISSUE TITLE
Error from person_editor.cgi found in the apache logs

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#74]
@azurebrd I found this error in the apache error log:

DBD::Pg::st execute failed: ERROR:  invalid regular expression: parentheses () not balanced at /usr/lib/priv/cgi-bin/cecilia/person_editor.cgi line 174.
Cannot prepare statement: ERROR:  invalid regular expression: parentheses () not balanced

**Comment by azurebrd** [comment]
It's just an autocomplete and Cecilia hasn't complained about not finding matches, I don't think it matters.
