### ISSUE TITLE
Migrate acknowledge prod to caltech-curation-services prod

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#77]
The EC2 instance used for acknowledge prod is very small and it's running out of space. Migrating all acknowledge services to caltech-curation-services will make it easier to manage deployment

**Comment by valearna** [comment]
ssl certificates for acknowledge prod copied over to caltech-curation prod. Need to install the acknowledge suite and then change dns entries to point to the new server, then if everything works delete EC2 instance:

- [ ] install acknowledge on caltech-curation
- [ ] set up jenkins for acknowledge on caltech-curation
- [ ] change dns entries
- [ ] remove old EC2 instance

**Comment by valearna** [comment]
The migration is done @vanaukenk @draciti. Everything looks good to me but let me know if you can access the prod dashboard and the submission form.

**Comment by draciti** [comment]
Thanks @valearna.
I can reach the production dashboard but not the submission form

<img width="617" alt="Screenshot 2023-12-12 at 9 19 59 AM" src="https://github.com/WormBase/caltech-curation-services/assets/901243/308f4019-260a-46de-960e-c3a1006e5710">

**Comment by valearna** [comment]
Fixed the issue that @draciti found by setting https in the base url for the dashboard. Now working on making the API more stable by deploying it using gunicorn instead of the default falcon server, which is not prod ready

**Comment by valearna** [comment]
Done. The api should be stable now both on dev and prod. Let me know if you get any error messages in the future @draciti @vanaukenk

**Comment by draciti** [comment]
thank you @valearna . Feel free to close if everything is taken care of. We can open new tickets if we encounter problems

**Comment by valearna** [comment]
Thanks @draciti. Closing

**Comment by vanaukenk** [comment]
Thank you @valearna 
I can access the production dashboard and submission forms fine this morning.
When I first loaded the submission form for WBPaper00066011 this morning there was a red error message at the top of the page about not being able to access all the data, but reloading the page cleared that error message and I don't see anything incorrect about the data on each of the widgets.

**Comment by valearna** [comment]
Thanks @vanaukenk I saw the error message too when I opened the submission form from the new server for the first time. I think it's a cache issue as the api got a new URL, so this shouldn't be a problem for the authors.
