### ISSUE TITLE
Mount NFS volumes to curation_forms service so that curators can modify files needed by the cgis

### ISSUE THREAD

**Issue by valearna** [WormBase/caltech-curation-services#8]

**Comment by valearna** [comment]
Create directory structure within repo with readme files to explain file format etc.

**Comment by valearna** [comment]
@azurebrd we should take a look at the dir structure that I set up to understand if it's enough to accommodate all curators' needs

**Comment by valearna** [comment]
The definitions for the dir structure is here: https://github.com/WormBase/caltech-curation-services/tree/main/curation_forms/user_files

**Comment by azurebrd** [comment]
Thanks @valearna .  I think for the oa, that's the only thing that's needed.  We could check with Daniela (I can't find her username to tag her) about why the Paper info needs that information, but it seems you've got it worked out, so that's great.
